/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerticalsRouteImport } from './routes/verticals'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsTradeRouteImport } from './routes/verticals.trade'
import { Route as VerticalsIncubatorRouteImport } from './routes/verticals.incubator'
import { Route as VerticalsEcotourismRouteImport } from './routes/verticals.ecotourism'
import { Route as VerticalsCarbonRouteImport } from './routes/verticals.carbon'

const VerticalsRoute = VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsTradeRoute = VerticalsTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => VerticalsRoute,
} as any)
const VerticalsIncubatorRoute = VerticalsIncubatorRouteImport.update({
  id: '/incubator',
  path: '/incubator',
  getParentRoute: () => VerticalsRoute,
} as any)
const VerticalsEcotourismRoute = VerticalsEcotourismRouteImport.update({
  id: '/ecotourism',
  path: '/ecotourism',
  getParentRoute: () => VerticalsRoute,
} as any)
const VerticalsCarbonRoute = VerticalsCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => VerticalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/carbon': typeof VerticalsCarbonRoute
  '/verticals/ecotourism': typeof VerticalsEcotourismRoute
  '/verticals/incubator': typeof VerticalsIncubatorRoute
  '/verticals/trade': typeof VerticalsTradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/carbon': typeof VerticalsCarbonRoute
  '/verticals/ecotourism': typeof VerticalsEcotourismRoute
  '/verticals/incubator': typeof VerticalsIncubatorRoute
  '/verticals/trade': typeof VerticalsTradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/verticals': typeof VerticalsRouteWithChildren
  '/verticals/carbon': typeof VerticalsCarbonRoute
  '/verticals/ecotourism': typeof VerticalsEcotourismRoute
  '/verticals/incubator': typeof VerticalsIncubatorRoute
  '/verticals/trade': typeof VerticalsTradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/verticals'
    | '/verticals/carbon'
    | '/verticals/ecotourism'
    | '/verticals/incubator'
    | '/verticals/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/verticals'
    | '/verticals/carbon'
    | '/verticals/ecotourism'
    | '/verticals/incubator'
    | '/verticals/trade'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/verticals'
    | '/verticals/carbon'
    | '/verticals/ecotourism'
    | '/verticals/incubator'
    | '/verticals/trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  VerticalsRoute: typeof VerticalsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verticals': {
      id: '/verticals'
      path: '/verticals'
      fullPath: '/verticals'
      preLoaderRoute: typeof VerticalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/trade': {
      id: '/verticals/trade'
      path: '/trade'
      fullPath: '/verticals/trade'
      preLoaderRoute: typeof VerticalsTradeRouteImport
      parentRoute: typeof VerticalsRoute
    }
    '/verticals/incubator': {
      id: '/verticals/incubator'
      path: '/incubator'
      fullPath: '/verticals/incubator'
      preLoaderRoute: typeof VerticalsIncubatorRouteImport
      parentRoute: typeof VerticalsRoute
    }
    '/verticals/ecotourism': {
      id: '/verticals/ecotourism'
      path: '/ecotourism'
      fullPath: '/verticals/ecotourism'
      preLoaderRoute: typeof VerticalsEcotourismRouteImport
      parentRoute: typeof VerticalsRoute
    }
    '/verticals/carbon': {
      id: '/verticals/carbon'
      path: '/carbon'
      fullPath: '/verticals/carbon'
      preLoaderRoute: typeof VerticalsCarbonRouteImport
      parentRoute: typeof VerticalsRoute
    }
  }
}

interface VerticalsRouteChildren {
  VerticalsCarbonRoute: typeof VerticalsCarbonRoute
  VerticalsEcotourismRoute: typeof VerticalsEcotourismRoute
  VerticalsIncubatorRoute: typeof VerticalsIncubatorRoute
  VerticalsTradeRoute: typeof VerticalsTradeRoute
}

const VerticalsRouteChildren: VerticalsRouteChildren = {
  VerticalsCarbonRoute: VerticalsCarbonRoute,
  VerticalsEcotourismRoute: VerticalsEcotourismRoute,
  VerticalsIncubatorRoute: VerticalsIncubatorRoute,
  VerticalsTradeRoute: VerticalsTradeRoute,
}

const VerticalsRouteWithChildren = VerticalsRoute._addFileChildren(
  VerticalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  VerticalsRoute: VerticalsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
